site_name: Quarkus Agentic Workshop
repo_url: https://github.com/quarkusio/quarkus-workshop-agentic
edit_uri: edit/main/docs/
docs_dir: docs

nav:
  - Requirements: 'requirements.md'
  - Step 1 - Function Calling: 'step-01.md'
#  - Step 2 - MCP: Insurance Quote as External Tool 'step-02.md'
#  - Step 3 - Workflow Pattern: Routing: 'step-03.md'
#  - Step 4 - Orchestrator Pattern: Multi-Step Task: 'step-04.md'
#  - Step 5 - Advanced Orchestration: Multiple AI Services: 'step-05.md'
#  - Step 6 - A2A: Remote Specialist Agent (Pricing Agent): 'step-06.md'
#  - Step 7 - Guardrail: Prompt Injection Check: 'step-07.md'
#  - Step 8 - Observability: Metrics & Traces: 'step-08.md'
#  - Step 9 - Guardrails: 'step-09.md'
#  - Step 10 - Observability and Fault Tolerance: 'step-10.md'
  - Conclusion: 'conclusion.md'


theme:
  name: material
  custom_dir: mkdocs-customizations/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/lightbulb-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/lightbulb-on
        name: Switch to light mode
  font:
    text: Roboto
    code: Ubuntu Mono
  icon:
    repo: fontawesome/brands/github
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.sections
    - content.tabs.link
    - content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.footer
    - navigation.tabs.sticky
    - content.code.select
    - content.code.copy

extra_css:
  - extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - smarty
  - attr_list
  - md_in_html
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      check_paths: true
      base_path: !relative $docs_dir
      restrict_base_path: false
      dedent_subsections: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - build_plantuml:
      render: "server"
      server: "https://www.plantuml.com/plantuml"
      output_format: "svg"
      diagram_root: "docs"
      output_folder: "target"
      input_folder: "diagrams"
      input_extensions: "puml"
  - macros:
      verbose: true
      module_name: mkdocs-customizations/macros/docissimo
      include_dir: mkdocs-customizations/macros
  - mkdocs-video:
      is_video: True


extra:
  snippet_dir: ../
  manifest: manifest.webmanifest
  version:
    provider: mike
