name: Build

env:
  JVM_VERSION: '21'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - solution/parasol-service
          - solution/customer-mcp
          - solution/expert-agent
          # - steps/step01

    name: "Build ${{ matrix.app }}"
    steps:
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: temurin
          cache: maven
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '${{ matrix.app }}/src/main/webui/package-lock.json'
      - name: Install npm dependencies for UI
        if: matrix.app == 'solution/parasol-service'
        working-directory: ${{ matrix.app }}/src/main/webui
        run: npm install
      - name: Maven Build for ${{ matrix.app }}
        working-directory: ${{ matrix.app }}
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -DskipITs=false


  docs:
    runs-on: ubuntu-latest
    name: "Build Docs"
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - uses: actions/setup-java@v5
        name: Set up Java 21
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: temurin
          cache: maven

      - name: Generate documentation
        working-directory: docs
        run: |
          pip install pipenv
          pipenv install
          pipenv run mkdocs build --clean

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site