name: Build container image

env:
  JAVA_VERSION: '21'

on:
  workflow_run:
    workflows:
      - "Simple build and test"
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.workflow_run.head_branch || github.event.ref || github.ref }}"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-and-push:
    if: ((github.event_name == 'workflow_dispatch') || ((github.event_name == 'workflow_run') && ((github.event.workflow_run.event == 'push') || (github.event.workflow_run.event == 'workflow_dispatch')) && (github.event.workflow_run.conclusion == 'success'))) && ((github.repository == 'rh-rad-ai-roadshow/parasol-insurance') && ((github.event.workflow_run.head_branch == 'main')))
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: "build-and-push-app"
        working-directory: app
        run: |
          ./mvnw -B quarkus:add-extension -Dextensions="quarkus-container-image-podman" &&
          ./mvnw -B clean package -DskipTests \
            -Dquarkus.container-image.builder=podman \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.tag=latest \
            -Dquarkus.container-image.additional-tags=${{ github.sha }} \
            -Dquarkus.container-image.registry=quay.io \
            -Dquarkus.container-image.group=rhappsvcs \
            -Dquarkus.container-image.name=parasol-insurance \
            -Dquarkus.container-image.username=rhappsvcs+parasol \
            -Dquarkus.container-image.password=${{ secrets.REGISTRY_PASSWORD }} \
            -Dquarkus.podman.platform=linux/amd64,linux/arm64
