name: Simple build and test

on:
  push:
    branches:
      - main
      - email-feature-branch
      - private-docs-rag-solution
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/workflows/container-build.yml'
      - '.github/workflows/simple-build-test.yml'
      - '.github/workflows/dependabot-automerge.yml'
      - '.github/workflows/sync-main-to-other-branches.yml'
      - '.github/workflows/sync-to-ai-llm-template.yml'
  pull_request:
    branches:
      - main
      - email-feature-branch
      - private-docs-rag-solution
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/workflows/container-build.yml'
      - '.github/workflows/simple-build-test.yml'
      - '.github/workflows/dependabot-automerge.yml'
      - '.github/workflows/sync-main-to-other-branches.yml'
      - '.github/workflows/sync-to-ai-llm-template.yml'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  jvm-build-test:
    if: always() && !failure() && !cancelled()
    needs:
      - check-commit-against-main
      - check-commit-against-other-branch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '21'
        ai-provider:
          - ollama
          - jlama
          - openai
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
        options: --name ollama --rm
    name: "jvm-build-test-${{ matrix.java }}-${{ matrix.ai-provider }}"
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: "build-test-jvm-java${{ matrix.java }}-${{ matrix.ai-provider }}"
        if: matrix.ai-provider != 'openai'
        working-directory: app
        run: |
          ./mvnw -B clean verify \
            -P${{ matrix.ai-provider }} \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }}

      - name: "build-test-jvm-java${{ matrix.java }}-${{ matrix.ai-provider }}"
        if: matrix.ai-provider == 'openai'
        working-directory: app
        run: |
          docker exec ollama bash -c "ollama pull llama3.2 && ollama pull snowflake-arctic-embed && ollama ls"
          ./mvnw -B clean verify \
            -Dquarkus.http.host=0.0.0.0 \
            -Dquarkus.langchain4j.openai.base-url=http://localhost:11434/v1 \
            -Dquarkus.langchain4j.openai.parasol-chat.base-url=http://localhost:11434/v1 \
            -Dquarkus.langchain4j.openai.parasol-chat.chat-model.model-name=llama3.2 \
            -Dquarkus.langchain4j.openai.embedding-model.model-name=snowflake-arctic-embed \
            -Dmaven.compiler.release=${{ matrix.java }}

  check-commit-against-main:
    if: (github.event_name == 'pull_request') && (github.repository == 'rh-rad-ai-roadshow/parasol-insurance') && ((github.actor == 'dependabot[bot]') || (github.event.pull_request.user.login == 'dependabot[bot]')) && (github.base_ref != 'main')
    strategy:
      fail-fast: false
      matrix:
        java:
          - '21'
        ai-provider:
          - ollama
          - jlama
          - openai
    uses: rh-rad-ai-roadshow/parasol-insurance/.github/workflows/check-pr-against-other-branch.yml@main
    secrets: inherit
    with:
      java_version: ${{ matrix.java }}
      pr_num: ${{ github.event.pull_request.number }}
      ai_provider: ${{ matrix.ai-provider }}

  check-commit-against-other-branch:
    if: (github.event_name == 'pull_request') && (github.repository == 'rh-rad-ai-roadshow/parasol-insurance') && ((github.actor == 'dependabot[bot]') || (github.event.pull_request.user.login == 'dependabot[bot]')) && (github.base_ref == 'main')
    strategy:
      fail-fast: false
      matrix:
        java:
          - '21'
        ai-provider:
          - ollama
          - jlama
          - openai
        branch-to-check-against:
          - email-feature-branch
          - private-docs-rag-solution
    uses: rh-rad-ai-roadshow/parasol-insurance/.github/workflows/check-pr-against-other-branch.yml@main
    secrets: inherit
    with:
      java_version: ${{ matrix.java }}
      pr_num: ${{ github.event.pull_request.number }}
      ai_provider: ${{ matrix.ai-provider }}
      base_branch: ${{ matrix.branch-to-check-against }}
